---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentalservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentalservice
  template:
    metadata:
      labels:
        app: rentalservice
    spec:
      containers:
      - name: rentalservice
        image: mgokry/rentalservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: rentalservice
spec:
  selector:
    app: rentalservice
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prenomservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prenomservice
  template:
    metadata:
      labels:
        app: prenomservice
    spec:
      containers:
      - name: prenomservice
        image: mgokry/prenomservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: prenomservice
spec:
  selector:
    app: prenomservice
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
